export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS';
export const GET_CART_TOTAL ='GET_CART_TOTAL';
export const CLEAR_SHOPPING_CART = 'CLEAR_SHOPPING_CART';