export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESSFUL = 'GET_ALL_PRODUCTS_SUCCESSFFUL';
export const GET_ALL_PRODUCTS_FAILED = 'GET_ALL_PRODUCTS_FAILED';

export const GET_PRODUCTS_DETAILS_REQUEST = 'GET_PRODUCTS_DETAILS_REQUEST';
export const GET_PRODUCTS_DETAILS_SUCCESSFUL = 'GET_PRODUCTS_DETAILS_SUCCESSFFUL';
export const GET_PRODUCTS_DETAILS_FAILED = 'GET_PRODUCTS_DETAILS_FAILED';

export const CREATE_PRODUCT_REVIEW_REQUEST = 'CREATE_PRODUCT_REVIEW_REQUEST';
export const CREATE_PRODUCT_REVIEW_SUCCESSFUL = 'CREATE_PRODUCT_REVIEW_SUCCESSFUL';
export const CREATE_PRODUCT_REVIEW_FAILED = 'CREATE_PRODUCT_REVIEW_FAILED ';
export const CREATE_PRODUCT_REVIEW_RESET = 'CREATE_PRODUCT_REVIEW_RESET  ';