//  USER SIGNUP
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESSFUL = 'USER_SIGNUP_SUCCESSFFUL';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';

//  USER INFO
export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESSFUL = 'USER_INFO_SUCCESSFFUL';
export const USER_INFO_FAILED = 'USER_INFO_FAILED';

// USER LOGIN AND LOGOUT
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFFUL';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
